"use client";

import { useEffect, useMemo, useState } from "react";
import { ArrowDownToLine, ArrowUpFromLine, Lock, Repeat } from "lucide-react";
import { useSim } from "@/hooks/useSim";
import { useStore } from "@/store/useStore";
import { pushNotice } from "@/lib/yieldDesk";
import { VAULT_BY_ID, navAt, navHistory, type VaultSpec } from "@/lib/sim/vaults";
import { redemptionOpensAt } from "@/lib/sim/engine";
import { fmtPct, fmtUsdc, signClass } from "@/lib/sim/format";
import { cn } from "@/lib/utils";
import { Panel, Notice } from "./Panel";
import { NavChart } from "./NavChart";
import { RiskMeter, VaultCard, modelExpectedReturn, vaultStats } from "./VaultCard";

export function VaultDesk({ vaults, intro }: { vaults: VaultSpec[]; intro: React.ReactNode }) {
  const { account, epoch, actions } = useSim();
  const userId = useStore((s) => s.user?.id);
  const [selected, setSelected] = useState(vaults[0].id);
  const [mode, setMode] = useState<"deposit" | "withdraw">("deposit");
  const [amount, setAmount] = useState("");
  const [msg, setMsg] = useState<{ tone: "success" | "error"; text: string } | null>(null);

  useEffect(() => {
    const v = new URLSearchParams(window.location.search).get("vault");
    if (v && vaults.some((x) => x.id === v)) setSelected(v);
  }, [vaults]);

  const spec = VAULT_BY_ID[selected];
  const stats = useMemo(() => vaultStats(selected, epoch), [selected, epoch]);
  const history = useMemo(
    () => navHistory(selected, Math.max(0, epoch - 270), epoch).map((p) => ({ epoch: p.epoch, nav: p.nav * 1000 })),
    [selected, epoch],
  );

  if (!account) return null;
  const pos = account.vaults[selected];
  const posValue = pos ? pos.shares * stats.nav : 0;
  const opensAt = redemptionOpensAt(account, selected);
  const locked = !!pos && epoch < opensAt;
  const value = Number(amount) || 0;

  const submit = () => {
    setMsg(null);
    const res = mode === "deposit" ? actions.deposit(selected, value) : actions.withdraw(selected, value);
    if (res.ok) {
      const text = `${mode === "deposit" ? "Subscribed" : "Redeemed"} ${fmtUsdc(value)} USD ${mode === "deposit" ? "into" : "from"} ${spec.code}.`;
      setMsg({ tone: "success", text });
      if (userId) pushNotice(userId, mode === "deposit" ? "Capital allocated" : "Capital returned", text);
      setAmount("");
    } else {
      setMsg({ tone: "error", text: res.error });
    }
  };

  return (
    <div className="space-y-5">
      {intro}
      <div className="grid sm:grid-cols-2 xl:grid-cols-5 gap-3">
        {vaults.map((v) => (
          <VaultCard
            key={v.id}
            spec={v}
            epoch={epoch}
            positionValue={(account.vaults[v.id]?.shares ?? 0) * navAt(v.id, epoch)}
            selected={v.id === selected}
            onSelect={() => { setSelected(v.id); setMsg(null); }}
          />
        ))}
      </div>

      <div className="grid xl:grid-cols-[1fr_380px] gap-5">
        <Panel code={spec.code} title={spec.name} action={<RiskMeter level={spec.risk} />}>
          <p className="text-[14px] text-white/75 leading-relaxed">{spec.thesis}</p>
          <p className="text-[12.5px] text-white/45 mt-2 leading-relaxed">{spec.mechanics}</p>

          <div className="grid grid-cols-2 md:grid-cols-4 gap-3 mt-5 sim-num text-[12px]">
            {[
              ["NAV / share", stats.nav.toFixed(4), ""],
              ["30D return", fmtPct(stats.ret30d), signClass(stats.ret30d)],
              ["90D return", fmtPct(stats.ret90d), signClass(stats.ret90d)],
              ["Drawdown from peak", fmtPct(stats.drawdown, 1), stats.drawdown < -0.001 ? "sim-neg" : "text-white/70"],
              ["Realized vol", fmtPct(stats.vol, 1, false), "text-white/80"],
              ["Model E[r] (net)", fmtPct(modelExpectedReturn(spec), 1), signClass(modelExpectedReturn(spec))],
              ["Calm μ / σ", `${fmtPct(spec.calm.mu, 0)} / ${fmtPct(spec.calm.sigma, 0, false)}`, "text-white/70"],
              ["Stress μ / σ", `${fmtPct(spec.stress.mu, 0)} / ${fmtPct(spec.stress.sigma, 0, false)}`, "text-white/70"],
            ].map(([label, v, cls]) => (
              <div key={label} className="pnl-card pnl-card-pos">
                <p className="sim-label text-[8.5px] mb-1">{label}</p>
                <p className={cn("font-bold", cls || "text-white")}>{v}</p>
              </div>
            ))}
          </div>

          <p className="sim-label mt-6 mb-2">Growth of 1,000 USD · last 90 days</p>
          <NavChart history={history} height={200} />
          <p className="text-[11px] text-white/35 mt-3 leading-relaxed">
            The vault path is generated by a seeded regime-switching model that every user shares. Performance fees
            ({Math.round(spec.perfFee * 100)}%) are charged only on new highs above the vault&apos;s high-water mark and
            flow into the protocol fee pool.
          </p>
        </Panel>

        <Panel code="Allocation ticket" title={pos ? `Position · ${fmtUsdc(posValue)} USD` : "No position"} edge className="xl:sticky xl:top-20 self-start">
          <div className="grid grid-cols-2 gap-2 mb-4">
            <button type="button" onClick={() => setMode("deposit")} className={cn("sim-btn", mode === "deposit" ? "sim-btn-primary" : "sim-btn-ghost")}>
              <ArrowDownToLine className="w-4 h-4" /> Deposit
            </button>
            <button type="button" onClick={() => setMode("withdraw")} disabled={!pos} className={cn("sim-btn", mode === "withdraw" ? "bg-white text-black" : "sim-btn-ghost")}>
              <ArrowUpFromLine className="w-4 h-4" /> Redeem
            </button>
          </div>

          <label htmlFor="vault-amt" className="sim-label block mb-1.5">Amount (USD)</label>
          <input
            id="vault-amt"
            type="number"
            min="0"
            step="any"
            inputMode="decimal"
            value={amount}
            onChange={(e) => setAmount(e.target.value)}
            placeholder={mode === "deposit" ? `Min ${spec.minTicket.toLocaleString()}` : "0.00"}
            className="sim-input sim-num"
          />
          <div className="flex gap-1.5 mt-2">
            {[0.25, 0.5, 1].map((f) => (
              <button
                key={f}
                type="button"
                onClick={() => setAmount((Math.floor((mode === "deposit" ? account.cash : posValue) * f * 100) / 100).toString())}
                className="sim-chip cursor-pointer flex-1 justify-center"
              >
                {f === 1 ? "Max" : `${f * 100}%`}
              </button>
            ))}
          </div>

          <dl className="sim-num text-[11.5px] space-y-1.5 mt-4 border-t border-white/[0.05] pt-3">
            <div className="flex justify-between"><dt className="text-white/40">Free USD</dt><dd className="text-white">{fmtUsdc(account.cash)}</dd></div>
            <div className="flex justify-between"><dt className="text-white/40">Shares at NAV</dt><dd className="text-white">{value > 0 ? (value / stats.nav).toFixed(4) : "—"}</dd></div>
            {pos && (
              <>
                <div className="flex justify-between"><dt className="text-white/40">Cost basis</dt><dd className="text-white/70">{fmtUsdc(pos.costBasis)}</dd></div>
                <div className="flex justify-between"><dt className="text-white/40">Unrealized</dt><dd className={signClass(posValue - pos.costBasis)}>{fmtUsdc(posValue - pos.costBasis)}</dd></div>
              </>
            )}
            <div className="flex justify-between">
              <dt className="text-white/40">Redemption</dt>
              <dd className={locked ? "text-amber-300" : "text-white/70"}>
                {spec.lockEpochs === 0 ? "Instant" : locked ? `Opens epoch ${opensAt.toLocaleString()} (${opensAt - epoch} left)` : `${spec.lockEpochs / 3}D window after each deposit`}
              </dd>
            </div>
          </dl>

          {pos && (
            <button
              type="button"
              onClick={() => actions.toggleCompound(selected, !pos.autoCompound)}
              className="mt-4 w-full flex items-center justify-between rounded-xl border border-white/[0.08] bg-white/[0.02] px-3 py-2.5"
              aria-pressed={pos.autoCompound}
            >
              <span className="flex items-center gap-2 text-[12.5px] text-white/80">
                <Repeat className="w-3.5 h-3.5" /> Auto-compound fee share
              </span>
              <span className={cn("w-9 h-5 rounded-full p-0.5 transition-colors", pos.autoCompound ? "bg-emerald-500" : "bg-white/15")}>
                <span className={cn("block w-4 h-4 rounded-full bg-white transition-transform", pos.autoCompound && "translate-x-4")} />
              </span>
            </button>
          )}

          {msg && <Notice tone={msg.tone} className="mt-4">{msg.text}</Notice>}

          <button
            type="button"
            onClick={submit}
            disabled={!(value > 0) || (mode === "withdraw" && locked)}
            className={cn("sim-btn w-full mt-4", mode === "deposit" ? "sim-btn-primary" : "bg-white text-black")}
          >
            {mode === "withdraw" && locked ? <><Lock className="w-4 h-4" /> Redemption window closed</> : mode === "deposit" ? "Mint shares" : "Burn shares"}
          </button>
        </Panel>
      </div>
    </div>
  );
}
