/** Indicative reference marks for the broad equity book. Live feeds override these when a quote is present. */

type Row = [string, string, string, number];

const VOL: Record<string, number> = {
  Software: 0.32,
  Semiconductors: 0.42,
  Internet: 0.34,
  Financials: 0.22,
  Health: 0.24,
  Consumer: 0.22,
  Industrial: 0.24,
  Energy: 0.3,
  Staples: 0.16,
  Utilities: 0.16,
  RealEstate: 0.22,
  Materials: 0.26,
  Telecom: 0.2,
};

const ROWS: Row[] = [
  ["GOOGL", "Alphabet Class A", "Internet", 175],
  ["GOOG", "Alphabet Class C", "Internet", 176],
  ["AVGO", "Broadcom", "Semiconductors", 180],
  ["ORCL", "Oracle", "Software", 175],
  ["CRM", "Salesforce", "Software", 280],
  ["ADBE", "Adobe", "Software", 450],
  ["INTC", "Intel", "Semiconductors", 22],
  ["QCOM", "Qualcomm", "Semiconductors", 170],
  ["TXN", "Texas Instruments", "Semiconductors", 190],
  ["AMAT", "Applied Materials", "Semiconductors", 180],
  ["LRCX", "Lam Research", "Semiconductors", 80],
  ["KLAC", "KLA", "Semiconductors", 750],
  ["MU", "Micron", "Semiconductors", 100],
  ["SNPS", "Synopsys", "Software", 520],
  ["CDNS", "Cadence", "Software", 280],
  ["INTU", "Intuit", "Software", 650],
  ["NOW", "ServiceNow", "Software", 900],
  ["PANW", "Palo Alto Networks", "Software", 180],
  ["CRWD", "CrowdStrike", "Software", 320],
  ["FTNT", "Fortinet", "Software", 90],
  ["ADSK", "Autodesk", "Software", 280],
  ["ANET", "Arista Networks", "Software", 90],
  ["IBM", "IBM", "Software", 220],
  ["ACN", "Accenture", "Software", 350],
  ["CTSH", "Cognizant", "Software", 80],
  ["ADP", "Automatic Data Processing", "Software", 280],
  ["PAYX", "Paychex", "Software", 140],
  ["WDAY", "Workday", "Software", 250],
  ["TEAM", "Atlassian", "Software", 180],
  ["DDOG", "Datadog", "Software", 130],
  ["SNOW", "Snowflake", "Software", 160],
  ["NET", "Cloudflare", "Software", 90],
  ["ZS", "Zscaler", "Software", 190],
  ["OKTA", "Okta", "Software", 80],
  ["SHOP", "Shopify", "Internet", 90],
  ["PYPL", "PayPal", "Financials", 80],
  ["SQ", "Block", "Financials", 70],
  ["COIN", "Coinbase", "Financials", 220],
  ["HOOD", "Robinhood", "Financials", 32],
  ["UBER", "Uber", "Internet", 75],
  ["ABNB", "Airbnb", "Internet", 140],
  ["DASH", "DoorDash", "Internet", 160],
  ["BKNG", "Booking Holdings", "Internet", 4500],
  ["EXPE", "Expedia", "Internet", 160],
  ["NFLX", "Netflix", "Internet", 700],
  ["DIS", "Walt Disney", "Consumer", 110],
  ["CMCSA", "Comcast", "Telecom", 40],
  ["T", "AT&T", "Telecom", 22],
  ["VZ", "Verizon", "Telecom", 42],
  ["TMUS", "T-Mobile", "Telecom", 220],
  ["EA", "Electronic Arts", "Consumer", 150],
  ["TTWO", "Take-Two", "Consumer", 180],
  ["RBLX", "Roblox", "Internet", 45],
  ["SPOT", "Spotify", "Internet", 450],
  ["JPM", "JPMorgan Chase", "Financials", 220],
  ["BAC", "Bank of America", "Financials", 42],
  ["WFC", "Wells Fargo", "Financials", 65],
  ["C", "Citigroup", "Financials", 65],
  ["GS", "Goldman Sachs", "Financials", 520],
  ["MS", "Morgan Stanley", "Financials", 110],
  ["BLK", "BlackRock", "Financials", 950],
  ["SCHW", "Charles Schwab", "Financials", 72],
  ["AXP", "American Express", "Financials", 270],
  ["V", "Visa", "Financials", 310],
  ["MA", "Mastercard", "Financials", 500],
  ["BRK.B", "Berkshire Hathaway", "Financials", 450],
  ["SPGI", "S&P Global", "Financials", 500],
  ["MCO", "Moody's", "Financials", 450],
  ["ICE", "Intercontinental Exchange", "Financials", 155],
  ["CME", "CME Group", "Financials", 220],
  ["CB", "Chubb", "Financials", 270],
  ["PGR", "Progressive", "Financials", 240],
  ["TRV", "Travelers", "Financials", 240],
  ["ALL", "Allstate", "Financials", 180],
  ["MET", "MetLife", "Financials", 80],
  ["PRU", "Prudential", "Financials", 120],
  ["AIG", "AIG", "Financials", 78],
  ["AFL", "Aflac", "Financials", 105],
  ["USB", "U.S. Bancorp", "Financials", 48],
  ["PNC", "PNC Financial", "Financials", 180],
  ["TFC", "Truist", "Financials", 42],
  ["COF", "Capital One", "Financials", 170],
  ["BK", "Bank of New York Mellon", "Financials", 75],
  ["STT", "State Street", "Financials", 90],
  ["FITB", "Fifth Third", "Financials", 42],
  ["HBAN", "Huntington", "Financials", 16],
  ["KEY", "KeyCorp", "Financials", 16],
  ["RF", "Regions Financial", "Financials", 24],
  ["CFG", "Citizens Financial", "Financials", 42],
  ["NTRS", "Northern Trust", "Financials", 95],
  ["SYF", "Synchrony", "Financials", 60],
  ["ALLY", "Ally Financial", "Financials", 38],
  ["UNH", "UnitedHealth", "Health", 540],
  ["JNJ", "Johnson & Johnson", "Health", 160],
  ["LLY", "Eli Lilly", "Health", 800],
  ["MRK", "Merck", "Health", 100],
  ["ABBV", "AbbVie", "Health", 180],
  ["PFE", "Pfizer", "Health", 28],
  ["TMO", "Thermo Fisher", "Health", 540],
  ["ABT", "Abbott", "Health", 115],
  ["DHR", "Danaher", "Health", 240],
  ["BMY", "Bristol-Myers Squibb", "Health", 55],
  ["AMGN", "Amgen", "Health", 310],
  ["GILD", "Gilead", "Health", 90],
  ["CVS", "CVS Health", "Health", 60],
  ["CI", "Cigna", "Health", 320],
  ["ELV", "Elevance Health", "Health", 420],
  ["HUM", "Humana", "Health", 280],
  ["ISRG", "Intuitive Surgical", "Health", 520],
  ["SYK", "Stryker", "Health", 370],
  ["BSX", "Boston Scientific", "Health", 90],
  ["MDT", "Medtronic", "Health", 88],
  ["ZTS", "Zoetis", "Health", 175],
  ["VRTX", "Vertex", "Health", 460],
  ["REGN", "Regeneron", "Health", 900],
  ["MRNA", "Moderna", "Health", 40],
  ["BIIB", "Biogen", "Health", 180],
  ["ILMN", "Illumina", "Health", 110],
  ["IDXX", "IDEXX", "Health", 450],
  ["EW", "Edwards Lifesciences", "Health", 75],
  ["RMD", "ResMed", "Health", 230],
  ["DXCM", "DexCom", "Health", 80],
  ["ALGN", "Align Technology", "Health", 220],
  ["HCA", "HCA Healthcare", "Health", 360],
  ["WMT", "Walmart", "Staples", 85],
  ["COST", "Costco", "Staples", 900],
  ["PG", "Procter & Gamble", "Staples", 170],
  ["KO", "Coca-Cola", "Staples", 68],
  ["PEP", "PepsiCo", "Staples", 160],
  ["PM", "Philip Morris", "Staples", 130],
  ["MO", "Altria", "Staples", 55],
  ["MDLZ", "Mondelez", "Staples", 68],
  ["CL", "Colgate-Palmolive", "Staples", 95],
  ["KMB", "Kimberly-Clark", "Staples", 135],
  ["GIS", "General Mills", "Staples", 65],
  ["K", "Kellanova", "Staples", 70],
  ["HSY", "Hershey", "Staples", 175],
  ["SJM", "J.M. Smucker", "Staples", 115],
  ["KHC", "Kraft Heinz", "Staples", 32],
  ["STZ", "Constellation Brands", "Staples", 180],
  ["TAP", "Molson Coors", "Staples", 58],
  ["MNST", "Monster Beverage", "Staples", 55],
  ["EL", "Estee Lauder", "Consumer", 80],
  ["CLX", "Clorox", "Staples", 155],
  ["CHD", "Church & Dwight", "Staples", 105],
  ["TSN", "Tyson Foods", "Staples", 60],
  ["HRL", "Hormel", "Staples", 32],
  ["CAG", "Conagra", "Staples", 28],
  ["CPB", "Campbell's", "Staples", 42],
  ["SBUX", "Starbucks", "Consumer", 95],
  ["MCD", "McDonald's", "Consumer", 300],
  ["NKE", "Nike", "Consumer", 80],
  ["HD", "Home Depot", "Consumer", 390],
  ["LOW", "Lowe's", "Consumer", 250],
  ["TGT", "Target", "Consumer", 140],
  ["TJX", "TJX Companies", "Consumer", 115],
  ["ROST", "Ross Stores", "Consumer", 150],
  ["CMG", "Chipotle", "Consumer", 55],
  ["YUM", "Yum Brands", "Consumer", 140],
  ["DPZ", "Domino's", "Consumer", 430],
  ["MAR", "Marriott", "Consumer", 250],
  ["HLT", "Hilton", "Consumer", 240],
  ["RCL", "Royal Caribbean", "Consumer", 200],
  ["CCL", "Carnival", "Consumer", 22],
  ["NCLH", "Norwegian Cruise", "Consumer", 22],
  ["F", "Ford", "Industrial", 11],
  ["GM", "General Motors", "Industrial", 50],
  ["CAT", "Caterpillar", "Industrial", 380],
  ["DE", "Deere", "Industrial", 420],
  ["GE", "GE Aerospace", "Industrial", 180],
  ["HON", "Honeywell", "Industrial", 220],
  ["UNP", "Union Pacific", "Industrial", 240],
  ["UPS", "United Parcel Service", "Industrial", 120],
  ["FDX", "FedEx", "Industrial", 270],
  ["BA", "Boeing", "Industrial", 170],
  ["LMT", "Lockheed Martin", "Industrial", 520],
  ["RTX", "RTX", "Industrial", 120],
  ["NOC", "Northrop Grumman", "Industrial", 480],
  ["GD", "General Dynamics", "Industrial", 280],
  ["LHX", "L3Harris", "Industrial", 230],
  ["ETN", "Eaton", "Industrial", 320],
  ["EMR", "Emerson", "Industrial", 120],
  ["ITW", "Illinois Tool Works", "Industrial", 260],
  ["PH", "Parker-Hannifin", "Industrial", 650],
  ["ROK", "Rockwell Automation", "Industrial", 280],
  ["CMI", "Cummins", "Industrial", 340],
  ["PCAR", "PACCAR", "Industrial", 105],
  ["NSC", "Norfolk Southern", "Industrial", 240],
  ["CSX", "CSX", "Industrial", 34],
  ["WM", "Waste Management", "Industrial", 210],
  ["RSG", "Republic Services", "Industrial", 200],
  ["CARR", "Carrier", "Industrial", 70],
  ["OTIS", "Otis", "Industrial", 100],
  ["JCI", "Johnson Controls", "Industrial", 75],
  ["TT", "Trane Technologies", "Industrial", 370],
  ["IR", "Ingersoll Rand", "Industrial", 90],
  ["DOV", "Dover", "Industrial", 185],
  ["XYL", "Xylem", "Industrial", 125],
  ["AME", "AMETEK", "Industrial", 180],
  ["ROK", "Rockwell", "Industrial", 280],
  ["FAST", "Fastenal", "Industrial", 75],
  ["GWW", "W.W. Grainger", "Industrial", 1050],
  ["URI", "United Rentals", "Industrial", 750],
  ["PWR", "Quanta Services", "Industrial", 300],
  ["VRSK", "Verisk", "Industrial", 270],
  ["XOM", "Exxon Mobil", "Energy", 115],
  ["CVX", "Chevron", "Energy", 155],
  ["COP", "ConocoPhillips", "Energy", 110],
  ["EOG", "EOG Resources", "Energy", 125],
  ["SLB", "SLB", "Energy", 42],
  ["PSX", "Phillips 66", "Energy", 130],
  ["MPC", "Marathon Petroleum", "Energy", 160],
  ["VLO", "Valero", "Energy", 130],
  ["OXY", "Occidental", "Energy", 50],
  ["HES", "Hess", "Energy", 140],
  ["WMB", "Williams", "Energy", 50],
  ["KMI", "Kinder Morgan", "Energy", 25],
  ["OKE", "ONEOK", "Energy", 95],
  ["HAL", "Halliburton", "Energy", 30],
  ["BKR", "Baker Hughes", "Energy", 40],
  ["DVN", "Devon Energy", "Energy", 38],
  ["FANG", "Diamondback Energy", "Energy", 170],
  ["EQT", "EQT", "Energy", 40],
  ["CTRA", "Coterra", "Energy", 26],
  ["NEE", "NextEra Energy", "Utilities", 75],
  ["DUK", "Duke Energy", "Utilities", 110],
  ["SO", "Southern Company", "Utilities", 85],
  ["D", "Dominion Energy", "Utilities", 55],
  ["AEP", "American Electric Power", "Utilities", 95],
  ["EXC", "Exelon", "Utilities", 40],
  ["SRE", "Sempra", "Utilities", 85],
  ["XEL", "Xcel Energy", "Utilities", 68],
  ["ED", "Consolidated Edison", "Utilities", 100],
  ["WEC", "WEC Energy", "Utilities", 100],
  ["ES", "Eversource", "Utilities", 65],
  ["AWK", "American Water Works", "Utilities", 140],
  ["PEG", "Public Service Enterprise", "Utilities", 85],
  ["FE", "FirstEnergy", "Utilities", 42],
  ["ETR", "Entergy", "Utilities", 130],
  ["AEE", "Ameren", "Utilities", 90],
  ["CMS", "CMS Energy", "Utilities", 70],
  ["DTE", "DTE Energy", "Utilities", 125],
  ["PPL", "PPL", "Utilities", 33],
  ["CEG", "Constellation Energy", "Utilities", 240],
  ["VST", "Vistra", "Utilities", 120],
  ["LIN", "Linde", "Materials", 450],
  ["SHW", "Sherwin-Williams", "Materials", 370],
  ["APD", "Air Products", "Materials", 290],
  ["ECL", "Ecolab", "Materials", 250],
  ["NEM", "Newmont", "Materials", 45],
  ["FCX", "Freeport-McMoRan", "Materials", 42],
  ["NUE", "Nucor", "Materials", 140],
  ["STLD", "Steel Dynamics", "Materials", 130],
  ["DOW", "Dow", "Materials", 45],
  ["DD", "DuPont", "Materials", 80],
  ["PPG", "PPG Industries", "Materials", 125],
  ["VMC", "Vulcan Materials", "Materials", 260],
  ["MLM", "Martin Marietta", "Materials", 540],
  ["ALB", "Albemarle", "Materials", 90],
  ["CF", "CF Industries", "Materials", 85],
  ["MOS", "Mosaic", "Materials", 28],
  ["IFF", "IFF", "Materials", 85],
  ["BALL", "Ball Corporation", "Materials", 58],
  ["AVY", "Avery Dennison", "Materials", 190],
  ["AMCR", "Amcor", "Materials", 10],
  ["PKG", "Packaging Corp", "Materials", 210],
  ["IP", "International Paper", "Materials", 50],
  ["AMT", "American Tower", "RealEstate", 200],
  ["PLD", "Prologis", "RealEstate", 115],
  ["CCI", "Crown Castle", "RealEstate", 100],
  ["EQIX", "Equinix", "RealEstate", 850],
  ["SPG", "Simon Property", "RealEstate", 170],
  ["O", "Realty Income", "RealEstate", 58],
  ["PSA", "Public Storage", "RealEstate", 310],
  ["WELL", "Welltower", "RealEstate", 140],
  ["DLR", "Digital Realty", "RealEstate", 170],
  ["SBAC", "SBA Communications", "RealEstate", 230],
  ["AVB", "AvalonBay", "RealEstate", 220],
  ["EQR", "Equity Residential", "RealEstate", 72],
  ["VICI", "VICI Properties", "RealEstate", 32],
  ["EXR", "Extra Space Storage", "RealEstate", 160],
  ["ARE", "Alexandria Real Estate", "RealEstate", 100],
  ["INVH", "Invitation Homes", "RealEstate", 35],
  ["MAA", "Mid-America Apartment", "RealEstate", 155],
  ["ESS", "Essex Property", "RealEstate", 290],
  ["UDR", "UDR", "RealEstate", 45],
  ["KIM", "Kimco Realty", "RealEstate", 23],
  ["REG", "Regency Centers", "RealEstate", 72],
  ["HST", "Host Hotels", "RealEstate", 18],
  ["VTR", "Ventas", "RealEstate", 65],
  ["PEAK", "Healthpeak", "RealEstate", 22],
  ["BXP", "BXP", "RealEstate", 75],
  ["FRT", "Federal Realty", "RealEstate", 110],
  ["CPT", "Camden Property", "RealEstate", 120],
  ["ASML", "ASML", "Semiconductors", 800],
  ["TSM", "TSMC", "Semiconductors", 170],
  ["ARM", "Arm Holdings", "Semiconductors", 140],
  ["SMCI", "Super Micro", "Semiconductors", 40],
  ["MRVL", "Marvell", "Semiconductors", 80],
  ["ADI", "Analog Devices", "Semiconductors", 210],
  ["NXPI", "NXP", "Semiconductors", 230],
  ["MCHP", "Microchip", "Semiconductors", 70],
  ["ON", "ON Semiconductor", "Semiconductors", 65],
  ["MPWR", "Monolithic Power", "Semiconductors", 700],
  ["SWKS", "Skyworks", "Semiconductors", 85],
  ["QRVO", "Qorvo", "Semiconductors", 80],
  ["ENTG", "Entegris", "Semiconductors", 100],
  ["TER", "Teradyne", "Semiconductors", 120],
  ["KEYS", "Keysight", "Semiconductors", 160],
  ["TRMB", "Trimble", "Industrial", 65],
  ["GRMN", "Garmin", "Consumer", 180],
  ["ZBRA", "Zebra", "Industrial", 370],
  ["TEL", "TE Connectivity", "Industrial", 150],
  ["GLW", "Corning", "Industrial", 48],
  ["APH", "Amphenol", "Industrial", 70],
  ["JBL", "Jabil", "Industrial", 140],
  ["CDW", "CDW", "Software", 180],
  ["HPQ", "HP", "Software", 35],
  ["HPE", "Hewlett Packard Enterprise", "Software", 20],
  ["DELL", "Dell Technologies", "Software", 120],
  ["NTAP", "NetApp", "Software", 120],
  ["STX", "Seagate", "Software", 100],
  ["WDC", "Western Digital", "Software", 65],
  ["MDB", "MongoDB", "Software", 260],
  ["GTLB", "GitLab", "Software", 55],
  ["PATH", "UiPath", "Software", 13],
  ["BILL", "BILL Holdings", "Software", 55],
  ["HUBS", "HubSpot", "Software", 600],
  ["TWLO", "Twilio", "Software", 70],
  ["ZM", "Zoom", "Software", 75],
  ["DOCU", "DocuSign", "Software", 80],
  ["ESTC", "Elastic", "Software", 90],
  ["CFLT", "Confluent", "Software", 25],
  ["IOT", "Samsara", "Software", 45],
  ["APP", "AppLovin", "Software", 320],
  ["MSTR", "Strategy", "Software", 300],
  ["AKAM", "Akamai", "Software", 95],
  ["FFIV", "F5", "Software", 220],
  ["VRSN", "VeriSign", "Software", 190],
  ["GEN", "Gen Digital", "Software", 28],
  ["PTC", "PTC", "Software", 180],
  ["ANSS", "Ansys", "Software", 330],
  ["MANH", "Manhattan Associates", "Software", 270],
  ["EPAM", "EPAM", "Software", 200],
  ["GLOB", "Globant", "Software", 140],
  ["IT", "Gartner", "Software", 500],
  ["BR", "Broadridge", "Software", 230],
  ["FICO", "Fair Isaac", "Software", 1800],
  ["MSCI", "MSCI", "Financials", 560],
  ["NDAQ", "Nasdaq", "Financials", 78],
  ["CBOE", "Cboe", "Financials", 200],
  ["MKTX", "MarketAxess", "Financials", 230],
  ["IBKR", "Interactive Brokers", "Financials", 170],
  ["RJF", "Raymond James", "Financials", 160],
  ["LPLA", "LPL Financial", "Financials", 320],
  ["AMP", "Ameriprise", "Financials", 520],
  ["TROW", "T. Rowe Price", "Financials", 110],
  ["BEN", "Franklin Resources", "Financials", 20],
  ["IVZ", "Invesco", "Financials", 16],
  ["BX", "Blackstone", "Financials", 160],
  ["KKR", "KKR", "Financials", 130],
  ["APO", "Apollo", "Financials", 140],
  ["ARES", "Ares Management", "Financials", 160],
  ["CG", "Carlyle", "Financials", 50],
  ["OWL", "Blue Owl", "Financials", 20],
  ["BAM", "Brookfield Asset Management", "Financials", 55],
  ["BN", "Brookfield", "Financials", 55],
  ["FI", "Fiserv", "Financials", 180],
  ["FIS", "Fidelity National", "Financials", 80],
  ["GPN", "Global Payments", "Financials", 100],
  ["WEX", "WEX", "Financials", 180],
  ["JKHY", "Jack Henry", "Financials", 175],
  ["SSNC", "SS&C", "Financials", 80],
  ["AFRM", "Affirm", "Financials", 50],
  ["SOFI", "SoFi", "Financials", 14],
  ["UPST", "Upstart", "Financials", 50],
  ["MELI", "MercadoLibre", "Internet", 2000],
  ["SE", "Sea Limited", "Internet", 110],
  ["PDD", "PDD Holdings", "Internet", 120],
  ["BABA", "Alibaba", "Internet", 95],
  ["JD", "JD.com", "Internet", 35],
  ["BIDU", "Baidu", "Internet", 95],
  ["NU", "Nu Holdings", "Financials", 13],
  ["CPNG", "Coupang", "Internet", 24],
  ["EBAY", "eBay", "Internet", 65],
  ["ETSY", "Etsy", "Internet", 55],
  ["CHWY", "Chewy", "Internet", 30],
  ["CART", "Instacart", "Internet", 42],
  ["LYFT", "Lyft", "Internet", 14],
  ["PINS", "Pinterest", "Internet", 32],
  ["SNAP", "Snap", "Internet", 10],
  ["ROKU", "Roku", "Internet", 75],
  ["TTD", "Trade Desk", "Internet", 90],
  ["MTCH", "Match Group", "Internet", 35],
  ["IAC", "IAC", "Internet", 45],
  ["ZG", "Zillow", "Internet", 70],
  ["OPEN", "Opendoor", "Internet", 2],
  ["CVNA", "Carvana", "Consumer", 220],
  ["ABNB", "Airbnb", "Internet", 140],
  ["W", "Wayfair", "Consumer", 50],
  ["BBY", "Best Buy", "Consumer", 90],
  ["AZO", "AutoZone", "Consumer", 3200],
  ["ORLY", "O'Reilly Automotive", "Consumer", 1100],
  ["AAP", "Advance Auto Parts", "Consumer", 45],
  ["GPC", "Genuine Parts", "Consumer", 125],
  ["TSCO", "Tractor Supply", "Consumer", 55],
  ["ULTA", "Ulta Beauty", "Consumer", 390],
  ["RL", "Ralph Lauren", "Consumer", 220],
  ["TPR", "Tapestry", "Consumer", 70],
  ["VFC", "VF Corporation", "Consumer", 18],
  ["UAA", "Under Armour", "Consumer", 8],
  ["DECK", "Deckers", "Consumer", 140],
  ["CROX", "Crocs", "Consumer", 110],
  ["ONON", "On Holding", "Consumer", 50],
  ["LULU", "Lululemon", "Consumer", 280],
  ["NKE", "Nike", "Consumer", 80],
  ["SBUX", "Starbucks", "Consumer", 95],
  ["DRI", "Darden", "Consumer", 170],
  ["CMG", "Chipotle", "Consumer", 55],
  ["WING", "Wingstop", "Consumer", 280],
  ["SHAK", "Shake Shack", "Consumer", 110],
  ["CAVA", "Cava", "Consumer", 90],
  ["WSM", "Williams-Sonoma", "Consumer", 160],
  ["RH", "RH", "Consumer", 280],
  ["DHI", "D.R. Horton", "Consumer", 160],
  ["LEN", "Lennar", "Consumer", 150],
  ["PHM", "PulteGroup", "Consumer", 120],
  ["NVR", "NVR", "Consumer", 8500],
  ["TOL", "Toll Brothers", "Consumer", 140],
  ["MAS", "Masco", "Industrial", 75],
  ["FBHS", "Fortune Brands", "Industrial", 80],
  ["SWK", "Stanley Black & Decker", "Industrial", 80],
  ["SNA", "Snap-on", "Industrial", 330],
  ["LEG", "Leggett & Platt", "Industrial", 10],
  ["WHR", "Whirlpool", "Consumer", 100],
  ["MHK", "Mohawk", "Consumer", 130],
  ["NWL", "Newell Brands", "Consumer", 7],
  ["HAS", "Hasbro", "Consumer", 60],
  ["MAT", "Mattel", "Consumer", 18],
  ["POOL", "Pool Corporation", "Consumer", 340],
  ["WSO", "Watsco", "Industrial", 500],
  ["BLDR", "Builders FirstSource", "Industrial", 150],
  ["OC", "Owens Corning", "Materials", 170],
  ["FBIN", "Fortune Brands Innovations", "Industrial", 75],
  ["TREX", "Trex", "Materials", 65],
  ["AWI", "Armstrong World", "Industrial", 140],
  ["CSL", "Carlisle", "Industrial", 400],
  ["IEX", "IDEX", "Industrial", 210],
  ["NDSN", "Nordson", "Industrial", 230],
  ["GGG", "Graco", "Industrial", 85],
  ["LECO", "Lincoln Electric", "Industrial", 200],
  ["RRX", "Regal Rexnord", "Industrial", 150],
  ["AOS", "A.O. Smith", "Industrial", 75],
  ["WAB", "Wabtec", "Industrial", 180],
  ["ALK", "Alaska Air", "Industrial", 50],
  ["DAL", "Delta Air Lines", "Industrial", 60],
  ["UAL", "United Airlines", "Industrial", 80],
  ["LUV", "Southwest", "Industrial", 30],
  ["AAL", "American Airlines", "Industrial", 14],
  ["JBHT", "J.B. Hunt", "Industrial", 170],
  ["CHRW", "C.H. Robinson", "Industrial", 100],
  ["EXPD", "Expeditors", "Industrial", 120],
  ["ODFL", "Old Dominion", "Industrial", 190],
  ["SAIA", "Saia", "Industrial", 450],
  ["XPO", "XPO", "Industrial", 120],
  ["KNX", "Knight-Swift", "Industrial", 52],
  ["R", "Ryder", "Industrial", 150],
  ["CAR", "Avis Budget", "Consumer", 90],
  ["HTZ", "Hertz", "Consumer", 4],
  ["ABT", "Abbott", "Health", 115],
  ["BDX", "Becton Dickinson", "Health", 230],
  ["BAX", "Baxter", "Health", 35],
  ["STE", "STERIS", "Health", 230],
  ["TFX", "Teleflex", "Health", 160],
  ["COO", "CooperCompanies", "Health", 95],
  ["HOLX", "Hologic", "Health", 70],
  ["TECH", "Bio-Techne", "Health", 65],
  ["RVTY", "Revvity", "Health", 110],
  ["IQV", "IQVIA", "Health", 200],
  ["CRL", "Charles River", "Health", 180],
  ["DGX", "Quest Diagnostics", "Health", 155],
  ["LH", "Labcorp", "Health", 220],
  ["DVA", "DaVita", "Health", 155],
  ["UHS", "Universal Health", "Health", 190],
  ["THC", "Tenet", "Health", 150],
  ["MOH", "Molina", "Health", 320],
  ["CNC", "Centene", "Health", 65],
  ["HSIC", "Henry Schein", "Health", 70],
  ["CAH", "Cardinal Health", "Health", 120],
  ["MCK", "McKesson", "Health", 560],
  ["COR", "Cencora", "Health", 240],
  ["WBA", "Walgreens", "Health", 9],
  ["ZBH", "Zimmer Biomet", "Health", 105],
  ["WST", "West Pharmaceutical", "Health", 230],
  ["PODD", "Insulet", "Health", 250],
  ["INSP", "Inspire Medical", "Health", 160],
  ["PEN", "Penumbra", "Health", 220],
  ["GMED", "Globus Medical", "Health", 75],
  ["NVST", "Envista", "Health", 18],
  ["XRAY", "Dentsply Sirona", "Health", 18],
  ["OMI", "Owens & Minor", "Health", 12],
  ["CHE", "Chemed", "Health", 580],
  ["OPCH", "Option Care Health", "Health", 32],
  ["AMED", "Amedisys", "Health", 95],
  ["ENSG", "Ensign Group", "Health", 145],
  ["SGEN", "Seagen", "Health", 200],
  ["BMRN", "BioMarin", "Health", 70],
  ["ALNY", "Alnylam", "Health", 250],
  ["ARGX", "argenx", "Health", 600],
  ["NBIX", "Neurocrine", "Health", 130],
  ["EXAS", "Exact Sciences", "Health", 55],
  ["NTRA", "Natera", "Health", 140],
  ["GH", "Guardant Health", "Health", 35],
  ["VEEV", "Veeva", "Health", 210],
  ["TDOC", "Teladoc", "Health", 10],
  ["DOCS", "Doximity", "Health", 40],
  ["HIMS", "Hims & Hers", "Health", 20],
  ["OSCR", "Oscar Health", "Health", 18],
  ["SAP", "SAP", "Software", 230],
  ["NVO", "Novo Nordisk", "Health", 90],
  ["AZN", "AstraZeneca", "Health", 75],
  ["NVS", "Novartis", "Health", 110],
  ["SNY", "Sanofi", "Health", 52],
  ["GSK", "GSK", "Health", 40],
  ["RHHBY", "Roche", "Health", 38],
  ["SHEL", "Shell", "Energy", 70],
  ["TTE", "TotalEnergies", "Energy", 65],
  ["BP", "BP", "Energy", 33],
  ["BHP", "BHP", "Materials", 55],
  ["RIO", "Rio Tinto", "Materials", 65],
  ["VALE", "Vale", "Materials", 10],
  ["SCCO", "Southern Copper", "Materials", 100],
  ["GOLD", "Barrick", "Materials", 18],
  ["AEM", "Agnico Eagle", "Materials", 80],
  ["WPM", "Wheaton Precious", "Materials", 60],
  ["UL", "Unilever", "Staples", 60],
  ["DEO", "Diageo", "Staples", 120],
  ["BTI", "British American Tobacco", "Staples", 38],
  ["SONY", "Sony", "Consumer", 22],
  ["TM", "Toyota", "Industrial", 190],
  ["HMC", "Honda", "Industrial", 30],
  ["SONY", "Sony Group", "Consumer", 22],
];

export type UniverseRow = {
  symbol: string;
  name: string;
  sector: string;
  ref: number;
  vol: number;
};

const seen = new Set<string>();

export const EQUITY_UNIVERSE: UniverseRow[] = ROWS.flatMap(([symbol, name, sector, ref]) => {
  if (seen.has(symbol)) return [];
  seen.add(symbol);
  return [{ symbol, name, sector, ref, vol: VOL[sector] ?? 0.28 }];
});
